import { redirect } from "next/navigation";
import { getSupabaseAdmin } from "../../../lib/supabase-admin";

export default async function InquiriesPage() {
  const db=getSupabaseAdmin();
  const {data:{user}}=await db.auth.getUser();
  if(!user) redirect("/admin/login");
  const {data:profile}=await db.from("admin_profiles").select("active").eq("user_id",user.id).maybeSingle();
  if(!profile?.active) redirect("/admin/login");
  const {data:items}=await db.from("inquiries").select("id,parent_name,phone,email,grade,message,status,created_at").order("created_at",{ascending:false}).limit(100);
  const {data:visits}=await db.from("visit_requests").select("id,parent_name,phone,grade,preferred_date,status,created_at").order("created_at",{ascending:false}).limit(100);
  return <main className="min-h-screen bg-brand-alabaster px-5 py-10 text-brand-ink"><div className="mx-auto max-w-6xl"><a href="/admin" className="text-sm font-bold text-brand-teal-deep">← Dashboard</a><h1 className="mt-6 font-display text-4xl">Admissions desk</h1><p className="mt-3 text-sm text-brand-ink/55">Newest parent enquiries and visit requests.</p><section className="mt-8"><h2 className="font-display text-2xl">Enquiries</h2><div className="mt-4 overflow-x-auto border border-brand-border bg-white shadow-card"><table className="min-w-full text-left text-sm"><thead className="border-b border-brand-border bg-brand-mist"><tr><th className="px-4 py-3">Parent</th><th className="px-4 py-3">Grade</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Received</th></tr></thead><tbody>{(items??[]).map(x=><tr key={x.id} className="border-b border-brand-border/70"><td className="px-4 py-4"><div className="font-semibold">{x.parent_name}</div><div className="mt-1 max-w-md text-xs text-brand-ink/50">{x.message}</div></td><td className="px-4 py-4">{x.grade??"—"}</td><td className="px-4 py-4">{x.phone}</td><td className="px-4 py-4 capitalize">{x.status.replace("_"," ")}</td><td className="px-4 py-4 text-xs text-brand-ink/50">{new Date(x.created_at).toLocaleString("en-IN")}</td></tr>)}</tbody></table></div></section><section className="mt-10"><h2 className="font-display text-2xl">Visit requests</h2><div className="mt-4 overflow-x-auto border border-brand-border bg-white shadow-card"><table className="min-w-full text-left text-sm"><thead className="border-b border-brand-border bg-brand-mist"><tr><th className="px-4 py-3">Parent</th><th className="px-4 py-3">Grade</th><th className="px-4 py-3">Preferred date</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{(visits??[]).map(x=><tr key={x.id} className="border-b border-brand-border/70"><td className="px-4 py-4"><div className="font-semibold">{x.parent_name}</div><div className="mt-1 text-xs text-brand-ink/50">{x.phone}</div></td><td className="px-4 py-4">{x.grade}</td><td className="px-4 py-4">{x.preferred_date}</td><td className="px-4 py-4 capitalize">{x.status.replace("_"," ")}</td></tr>)}</tbody></table></div></section></div></main>;
}
